inherit_from: .rubocop_todo.yml

require:
  - rubocop-factory_bot
  - rubocop-rspec
  - rubocop-rspec_rails
  - rubocop-rails
  - rubocop-capybara

AllCops:
  NewCops: enable
  Exclude:
    - 'mock/**/*'
    - 'db/**/*'
    - 'bin/**/*'

Style/StringLiterals:
  Enabled: true
  EnforcedStyle: "double_quotes"

Style/Documentation:
  Enabled: false

# see https://github.com/rubocop/ruby-style-guide/issues/329
# I am team "if not" (when it makes sense)
Style/NegatedIf:
  Enabled: false

RSpec/NestedGroups:
  Max: 5

Style/HashSyntax:
  EnforcedShorthandSyntax: either
