ovh:
  service: S3
  access_key_id: <%= ENV.fetch("APLYPRO_S3_ACCESS_KEY_ID") %>
  secret_access_key: <%= ENV.fetch("APLYPRO_S3_SECRET_KEY_ID") %>
  endpoint: <%= ENV.fetch("APLYPRO_S3_ENDPOINT") %>
  region: <%= ENV.fetch("APLYPRO_S3_REGION") %>
  bucket: <%= ENV.fetch("APLYPRO_S3_BUCKET") %>

ovh_asp:
  service: S3
  access_key_id: <%= ENV.fetch("APLYPRO_S3_ACCESS_KEY_ID") %>
  secret_access_key: <%= ENV.fetch("APLYPRO_S3_SECRET_KEY_ID") %>
  endpoint: <%= ENV.fetch("APLYPRO_S3_ENDPOINT") %>
  region: <%= ENV.fetch("APLYPRO_S3_REGION") %>
  bucket: <%= ENV.fetch("APLYPRO_S3_PAYMENTS_BUCKET") %>
