name: ci

on:
  push:
    branches-ignore:
    - 'release/**'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true
      - uses: docker/setup-buildx-action@v3
      - uses: docker/build-push-action@v5
        with:
          context: .
          tags: aplypro:latest
          outputs: type=docker,dest=/tmp/aplypro.tar
          cache-from: type=gha
          cache-to: type=gha,mode=max
      -
        name: Cache image and ENV file
        id: aplypro-docker
        uses: actions/cache@v4
        with:
          path: |
            /tmp/aplypro.tar
            ./.github/workflows/test.env
          key: ${{ github.sha }}-aplypro
  build-mock:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true
      - uses: docker/setup-buildx-action@v3
      - uses: docker/build-push-action@v5
        with:
          context: ./mock
          tags: aplypro-mock:latest
          outputs: type=docker,dest=/tmp/aplypro-mock.tar
          cache-from: type=gha,scope=mock
          cache-to: type=gha,mode=max,scope=mock
      -
        name: Cache mock image
        uses: actions/cache@v4
        with:
          path: /tmp/aplypro-mock.tar
          key: ${{ github.sha }}-aplypro-mock
  lint:
    name: "Linting: Rubocop"
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: docker/setup-buildx-action@v3
      - uses: actions/cache@v4
        with:
          path: |
            /tmp/aplypro.tar
            ./.github/workflows/test.env
          key: ${{ github.sha }}-aplypro
      - run: docker load --input /tmp/aplypro.tar
      - run: docker run --rm --entrypoint="" aplypro:latest bundle exec rubocop
  unit-tests:
    name: "Unit tests: RSpec"
    runs-on: ubuntu-latest
    needs: [build, build-mock]
    services:
      postgres:
        image: postgres
        ports: ["5432:5432"]
        env:
          POSTGRES_PASSWORD: dummy
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    steps:
      - uses: docker/setup-buildx-action@v3
      - uses: actions/cache@v4
        with:
          path: |
            /tmp/aplypro.tar
            ./.github/workflows/test.env
          key: ${{ github.sha }}-aplypro
      - uses: actions/cache@v4
        with:
          path: /tmp/aplypro-mock.tar
          key: ${{ github.sha }}-aplypro-mock
      - run: docker load --input /tmp/aplypro.tar
      - run: docker load --input /tmp/aplypro-mock.tar
      - name: Start mock server
        run: docker run -d --name mock --network="host" aplypro-mock:latest
      - run: |
          docker run \
            --network="host" \
            --add-host="mock:127.0.0.1" \
            --env-file ./.github/workflows/test.env \
            --rm aplypro bundle exec rspec
  integration-tests:
    name: "Integration tests: Cucumber"
    runs-on: ubuntu-latest
    needs: [build, build-mock]
    services:
      postgres:
        image: postgres
        ports: ["5432:5432"]
        env:
          POSTGRES_PASSWORD: dummy
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    steps:
      - uses: docker/setup-buildx-action@v3
      - uses: actions/cache@v4
        with:
          path: |
            /tmp/aplypro.tar
            ./.github/workflows/test.env
          key: ${{ github.sha }}-aplypro
      - uses: actions/cache@v4
        with:
          path: /tmp/aplypro-mock.tar
          key: ${{ github.sha }}-aplypro-mock
      - run: docker load --input /tmp/aplypro.tar
      - run: docker load --input /tmp/aplypro-mock.tar
      - name: Start mock server
        run: docker run -d --name mock --network="host" aplypro-mock:latest
      - run: |
          docker run \
            --network="host" \
            --add-host="mock:127.0.0.1" \
            --env-file ./.github/workflows/test.env \
            --rm aplypro bundle exec cucumber
